version: '3.4'

services:
  basketdb:
    image: basketdb
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - "6379:6379"

  ordering.api:
    image: orderingapi
    build:
      context: .
      dockerfile: Dockerfile.orderingApi

  basket.api:
    image: basketapi
    build:
      context: .
      dockerfile: Dockerfile.basketApi


