#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["server/VectorShopApp.API/src/Authentication/Identity.API/Identity.API.csproj", "Authentication/Identity.API/"]
COPY ["server/VectorShopApp.API/src/Authentication/Identity.Application/Identity.Application.csproj", "Authentication/Identity.Application/"]
COPY ["server/VectorShopApp.API/src/Authentication/Identity.Domain/Identity.Domain.csproj", "Authentication/Identity.Domain/"]
COPY ["server/VectorShopApp.API/src/Authentication/Identity.Infrastucture/Identity.Infrastucture.csproj", "Authentication/Identity.Infrastucture/"]
RUN dotnet restore "Authentication/Identity.API/Identity.API.csproj"

WORKDIR "/src/Authentication/Identity.API"
COPY server/VectorShopApp.API/src/Authentication/Identity.API/ ./
COPY server/VectorShopApp.API/src/Authentication/Identity.Application/ ./
COPY server/VectorShopApp.API/src/Authentication/Identity.Domain/ ./
COPY server/VectorShopApp.API/src/Authentication/Identity.Infrastucture/ ./

RUN dotnet build "Identity.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Identity.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Identity.API.dll"]
