version: '3.4'

services:
  basketdb:
    image: redis

  ordering.api:
    image: orderingapi
    build:
      context: .
      dockerfile: Dockerfile.orderingApi

  basket.api:
    image: basketapi
    build:
      context: .
      dockerfile: Dockerfile.basketApi



