version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management-alpine

  authendb:
    image: mcr.microsoft.com/mssql/server
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Dockerfile.basketApi



