version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management-alpine

  authendb:
    image: mcr.microsoft.com/mssql/server

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Dockerfile.basketApi

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Dockerfile.catalogApi


  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: Dockerfile.ApiGateway


  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Dockerfile.authenApi