version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management-alpine

  authendb:
    image: mcr.microsoft.com/mssql/server
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: server/VectorShopApp.API/src/Basket/Basket.API/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: server/VectorShopApp.API/src/Catalog/Catalog.API/Dockerfile


  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: server/VectorShopApp.API/src/ApiGateway/OcelotApiGateway/Dockerfile


  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: server/VectorShopApp.API/src/Authentication/Identity.API/Dockerfile

